Repository 2023-Summer-Bootcamp-TeamC/SHOTPING-frontend, pull requests merged in 2023-07, with the labels that each got.

#2 [Feat/#1] 프론트엔드 기초세팅 완료
  .eslintrc.js
  .gitignore
  .prettierrc
  Dockerfile
  README.md
  README.old.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/setupTests.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: chore

#9 [design/#6] 결제완료 및 모달, 결제실패 퍼블리싱 완료
  package-lock.json
  package.json
  src/components/Pay/PayButton.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/components/Pay/PayText.tsx
  src/components/images/image001.png
  src/components/images/pay_image.png
  src/components/images/payfail_image.png
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  tailwind.config.js
Labels: design

#11 [design/#10] 사진인식 페이지 퍼블리싱 완료
  package-lock.json
  package.json
  src/components/scan/Feedback.tsx
  src/components/scan/ScanList.tsx
  src/components/scan/ScanResult.tsx
  src/components/scan/ScanStart.tsx
  src/components/scan/Scanning.tsx
  src/pages/ScanPage.tsx
  tailwind.config.js
Labels: design

#15 [refactor] 상단바 리팩토링 완료
  src/App.tsx
  src/components/layout/Header.tsx
  src/components/list/Modal.tsx
  src/components/list/ProductBox.tsx
  src/components/scan/ScanResult.tsx
  src/pages/ListPage.tsx
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  src/pages/ScanPage.tsx
Labels: refactor

#19 [design/#14] 메인, 리스트 배율 수정 완료
  package-lock.json
  package.json
  src/components/list/Modal.tsx
  src/components/list/ProductBox.tsx
  src/components/list/SearchBox.tsx
  src/components/main/MainModal.tsx
  src/pages/ListPage.tsx
  src/pages/MainPage.tsx
Labels: design

#20 [design/#10] 장바구니 페이지 및 모달 퍼블리싱 완료
  src/components/Buy/BuyList.tsx
  src/components/Buy/BuyModal.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/pages/BuyPage.tsx
  src/pages/PayPage.tsx
Labels: design

#24 [design] 검색결과 페이지 퍼블리싱 및 라우팅 완료
  src/App.tsx
  src/components/layout/Header.tsx
  src/components/list/SearchBox.tsx
  src/components/search/SearchProductList.tsx
  src/pages/SearchResultPage.tsx
Labels: design

#35 feat: 메인 페이지 반응형 구현완료
  src/components/main/MainModal.tsx
  src/components/main/ranking.tsx
  src/pages/MainPage.tsx
Labels: feat

#36 [feat/#29] 리스트. 결제관련 페이지 반응형 구현
  package-lock.json
  package.json
  src/components/Buy/BuyList.tsx
  src/components/Buy/BuyModal.tsx
  src/components/Pay/PayButton.tsx
  src/components/Pay/PayText.tsx
  src/components/common/Loading.tsx
  src/components/list/Modal.tsx
  src/components/list/ProductBox.tsx
  src/components/list/ProductKey.tsx
  src/components/list/SearchBox.tsx
  src/components/scan/Feedback.tsx
  src/components/scan/ScanList.tsx
  src/components/scan/ScanResult.tsx
  src/components/scan/Scanning.tsx
  src/components/search/SearchProductList.tsx
  src/pages/ListPage.tsx
  src/pages/MainPage.tsx
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  src/pages/ScanPage.tsx
  src/pages/SearchResultPage.tsx
Labels: feat

#42 [feat/#34] redux 연결 완료
  src/components/Buy/BuyList.tsx
  src/components/Pay/PayModalList.tsx
  src/components/list/Modal.tsx
  src/components/list/ProductBox.tsx
  src/components/list/ProductKey.tsx
  src/components/scan/ScanResult.tsx
  src/components/search/SearchProductList.tsx
  src/index.tsx
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  src/store/productSlice.tsx
  src/store/store.ts
Labels: feat

#44 [feat/#41] 상품 결제 api 연결 완료 및 결제완료 실패 페이지 로티 추가
  src/assets/lottie/CircleCheck.json
  src/assets/lottie/CircleClose.json
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
Labels: feat

#49 [refactor/#47] 상품인식 페이지, 상품리스트 페이지 리팩토링 완료
  src/assets/lottie/LoadingLottie.json
  src/assets/lottie/WarningLottie.json
  src/components/common/Loading.tsx
  src/components/layout/Header.tsx
  src/components/list/ProductBox.tsx
  src/components/list/ProductKey.tsx
  src/components/list/SearchBox.tsx
  src/components/scan/ScanResult.tsx
  src/pages/ScanFailPage.tsx
Labels: refactor

#51 [refactor] 인식 페이지 결과 컴포넌트 리스트 부분 보완 완료
  src/components/scan/ScanList.tsx
Labels: refactor

#56 [refactor/#45] buy,pay,payfail 페이지 리팩토링
  src/components/Buy/BuyList.tsx
  src/components/Buy/BuyModal.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/components/images/image001.png
  src/components/images/pay_image.png
  src/components/images/payfail_image.png
  src/components/list/ProductList.tsx
  src/pages/BuyPage.tsx
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  src/store/productSlice.tsx
Labels: refactor

#61 [refactor/#60] 결제 페이지, 결제실패 페이지 컴포넌트 분리 및 타 컴포넌트 필요없는 변수 주석 정리 완료
  src/components/Buy/BuyList.tsx
  src/components/Pay/PayFailLayout.tsx
  src/components/Pay/PayLayout.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/components/common/Loading.tsx
  src/components/layout/Header.tsx
  src/components/list/Modal.tsx
  src/components/main/MainModal.tsx
  src/components/scan/ScanResult.tsx
  src/pages/PayFailPage.tsx
  src/pages/PayPage.tsx
  src/store/productSlice.tsx
  src/store/store.ts
Labels: refactor

#63 [refactor/#57] BuyPage 컴포넌트 분리 리팩토링 완료
  src/components/Buy/BuyButton.tsx
  src/components/Buy/BuyInfo.tsx
  src/components/Buy/BuyList.tsx
  src/components/Buy/BuyModal.tsx
  src/components/Buy/LeftList.tsx
  src/components/Buy/LeftTab.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/pages/BuyPage.tsx
Labels: refactor

#65 [fix/#64] 피드백 컴포넌트 기능 수정 및 interface 복구 완료
  src/components/Buy/BuyButton.tsx
  src/components/Buy/BuyInfo.tsx
  src/components/Buy/BuyList.ts
  src/components/Buy/LeftList.tsx
  src/components/Buy/LeftTab.tsx
  src/components/scan/ScanResult.tsx
  src/pages/MainPage.tsx
  src/pages/ScanFailPage.tsx
Labels: fix

#67 [fix/#66] 장바구니 로직 수정 완료
  src/App.tsx
  src/components/Buy/BuyButton.tsx
  src/components/Buy/LeftList.tsx
  src/components/Buy/LeftTab.tsx
  src/components/Pay/NowPayingLayout.tsx
  src/components/Pay/PayLayout.tsx
  src/components/Pay/PayModalList.tsx
  src/components/common/Loading.tsx
  src/components/layout/Header.tsx
  src/components/list/Modal.tsx
  src/components/scan/ScanResult.tsx
  src/pages/NowPayingPage.tsx
  src/store/productSlice.tsx
Labels: fix

#75 [design/#74] 상품인식 결과 컴포넌트 사이즈 줄었을 때 버튼 위치 바뀐 것 수정
  src/components/scan/ScanResult.tsx
Labels: design

#77 [design/#69] BuyPage 반응형 및 결제 버튼 수정 완료
  src/components/Buy/BuyButton.tsx
  src/components/Buy/BuyInfo.tsx
  src/components/Buy/LeftList.tsx
  src/components/Buy/LeftTab.tsx
  src/pages/BuyPage.tsx
Labels: design

#81 [design/#80] 체크리스트 퍼블리싱 완료
  src/components/common/CheckList.tsx
  src/components/layout/Header.tsx
  src/components/list/ProductBox.tsx
Labels: design

#86 [feat/#82] 체크리스트 Redux 연결 완료
  src/components/common/CheckList.tsx
  src/components/layout/Header.tsx
  src/store/productSlice.tsx
Labels: feat

#87 [feat/#83] 상품 인식 결과 리스트 개수 부분, 인식된 거 없을 시 네비게이트 수정완료
  src/components/scan/ScanList.tsx
  src/components/scan/ScanResult.tsx
Labels: feat

#94 [refactor/#92] ScanResult파일 및 buy, pay와 관련된 코드 리팩토링 완료
  src/components/Buy/BuyButton.tsx
  src/components/Buy/BuyInfo.tsx
  src/components/Buy/BuyModal.tsx
  src/components/Buy/LeftList.tsx
  src/components/Buy/LeftTab.tsx
  src/components/Pay/NowPayingLayout.tsx
  src/components/Pay/PayFailLayout.tsx
  src/components/Pay/PayLayout.tsx
  src/components/Pay/PayModal.tsx
  src/components/Pay/PayModalList.tsx
  src/components/scan/ScanResult.tsx
  src/pages/BuyPage.tsx
  src/pages/NowPayingPage.tsx
  src/pages/ScanFailPage.tsx
Labels: refactor

#96 [design/#95] 리스트 페이지 밑에 하얀색 부분 안보이게 수정 완료
  src/pages/ListPage.tsx
Labels: design

#102 [feat/#100] 리스트 페이지에 '이미 담은 상품+새로 담으려는 수>재고' 일때 경고창 구현
  src/components/list/Modal.tsx
Labels: feat

#103 [fix/#88] 상품 인식 피드백 부분 수정 완료
  src/components/Buy/LeftList.tsx
  src/components/common/CheckList.tsx
  src/components/layout/Header.tsx
  src/components/main/MainLayout.tsx
  src/components/scan/ScanResult.tsx
Labels: fix, feat
